services:
  web:
    image: web:latest
    build:
      context: .
      dockerfile: Dockerfile
    container_name: web
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: "production"
      PORT: "3000"
    restart: unless-stopped
